FROM node:18 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY / ./

RUN npm run build

FROM node:18

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/build /app/build

EXPOSE 80

CMD ["serve", "-s", "build", "-l", "80"]
